### ISSUE TITLE
[기능 추가] 글 작성하기 

### ISSUE THREAD

**Issue by haedal-uni** [dal-cho/adme-front#13]

**Comment by haedal-uni** [comment]
<img src = https://user-images.githubusercontent.com/74857364/151375021-23e1b7e3-e4ad-4c86-b5af-50684bda2d40.png width="90%">

<br>

문제점 : 상단 바 공감공간, 문의하기 부분이 한 줄에 안나옴

**Comment by great-psycho** [comment]
그건 폰트 사이즈를 줄여주면 될거같습니다.

**Comment by haedal-uni** [comment]
완료
