### ISSUE TITLE
[오류] 로그인 페이지 css 적용x 

### ISSUE THREAD

**Issue by haedal-uni** [dal-cho/adme-front#30]
로그인 css 적용이 되지 않는 문제를 해결하기 위해
여러가지 방법을 시도하던 중

application을 실행하지 않고 html만 실행했을 때 

![image](https://user-images.githubusercontent.com/74857364/161324643-fab74ed3-6b1f-45ff-be7b-a9ba369b97bf.png)

~ blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

위와 같은 에러가 발생하여 구글에 검색을 해본 결과

실제 http 리퀘스트를 전송하는 코드에서는 위에서 선언한 루트 URL을 뺀 나머지 부분을 요청하면 된다는 글이 있어서 

**home.html** 에 url을 
url: `http://localhost:8080/login`, 대신 
url: `/login`, 으로 변경해봤습니다.

<img src = https://user-images.githubusercontent.com/74857364/161325451-95f67271-2ae8-4a86-941a-de249d432955.png width="40%">  

실제 application을 사용할 때는 위와 같은 에러는 없었으나
html 자체를 크롬으로 띄울 때 발생하여 사용해봤는데 어떻게 하는게 나을까요??

해당 자료 >> [React CORS 문제 해결하기(Proxy 이용)](https://snowdeer.github.io/openshift/2020/06/13/react-for-cors-using-proxy/)

**Comment by great-psycho** [comment]
음... application으로 돌릴때를 기준으로 하면 되지 않을까 생각합니다.

**Comment by haedal-uni** [comment]
넵
